#pragma once

#include <ros/console.h>
#include <ros/ros.h>
#include <humap_local_planner/HumapPlannerConfig.h> //!< Dynamic reconfigure struct
#include <humap_local_planner/humap_config.h> //!< Base class containing configuration

namespace humap_local_planner {

class HumapConfigROS: public HumapConfig {
public:
	HumapConfigROS() = default;
	virtual ~HumapConfigROS() = default;

	/**
	 * @brief Loads params from ROS parameter server
	 * @param nh: local ros::NodeHandle (searches for parameters in the @ref nh's namespace)
	 */
	void loadFromParamServer(const ros::NodeHandle& nh);

	/**
	 * @brief Reconfigures params from the dynamic_reconfigure config.
	 * @param cfg: Config class autogenerated by dynamic_reconfigure according to the cfg-file mentioned above.
	 */
	void reconfigure(HumapPlannerConfig& cfg);

	std::string odom_topic; //!< Topic name of the odometry message, provided by the robot driver or simulator
	std::string map_frame; //!< Global planning frame
private:
	std::mutex config_mutex_; //!< Mutex for config accesses and changes
};

typedef std::shared_ptr<const HumapConfigROS> HumapConfigROSConstPtr;

} /* namespace humap_local_planner */
