function [vel] = computeBaseVelocityFromPoses(pose1, pose2, dt)
%COMPUTEVELOCITYFROMPOSES Summary of this function goes here
%   Detailed explanation goes here
    
    % a.k.a. 'subtractPoses'
    displacement = [...
        pose2(1) - pose1(1), ...
        pose2(2) - pose1(2), ...
        pose2(3) - pose1(3) ...
    ];

    theta = pose1(3);
    vel = [...
        +displacement(1) / dt * cos(theta) + displacement(2) / dt * sin(theta);
        -displacement(1) / dt * sin(theta) + displacement(2) / dt * cos(theta);
        +displacement(3) / dt ...
    ];
end
